### ISSUE TITLE
zsh is slow when in /development/CheckProcessor directory

### ISSUE THREAD

**Issue by miroslawmajka** [logicnow/development-docker#2]
Any reason the VM ssh session boots into zsh instead of bash?
This shell seems slow in response when cd-ing into /development/CheckProcessor.
When launching bash and doing the same thing in the ssh session the lagging is gone.

**Comment by ianlgibbons** [comment]
Yes, it's basically doing a git status command in the background so you get a lovely status icon at your command prompt

**Comment by luissantos** [comment]
https://jijoejv.wordpress.com/2012/06/22/workaround-slowness-of-oh-my-zsh-git-plugins-on-large-repositories/
http://marc-abramowitz.com/archives/2012/04/10/fix-for-oh-my-zsh-git-svn-prompt-slowness/

Can you please fix it and open a pull request?

Thanks.
